Please note, this project utilises the pre-supplied default conda environment within ArcGIS Pro called arcgispro-py3.

The environment file is too large to host on GitHub.com. Users must use the supplied environment within their installation of ArcGIS Pro 3.XX.